{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "test-application.fullname" . }}
  labels:
    {{- include "test-application.labels" . | nindent 4 }}
  annotations:
    description: "Network policy for {{ include "test-application.fullname" . }} defining allowed traffic flows"
spec:
  podSelector:
    matchLabels:
      {{- include "test-application.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  
  # INGRESS RULES - What traffic is allowed TO this application
  ingress:
    {{- if .Values.networkPolicy.ingress.allowFromIngressController }}
    # Allow traffic from the Ingress Controller (nginx)
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-nginx  # Adjust based on your ingress-nginx namespace label
      ports:
        - protocol: TCP
          port: {{ .Values.app.port }}  # Application port (3000)
    {{- end }}
    
    {{- if .Values.networkPolicy.ingress.allowFromMonitoring }}
    # Allow monitoring scraping (Prometheus, etc.)
    - from:
      - namespaceSelector:
          matchLabels:
            name: monitoring  # Adjust based on your monitoring namespace
      ports:
        - protocol: TCP
          port: {{ .Values.metrics.port }}  # Metrics port
    {{- end }}
    
    {{- if .Values.networkPolicy.ingress.allowFromSameNamespace }}
    # Allow traffic from other pods in the same namespace
    - from:
      - namespaceSelector:
          matchLabels:
            name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.app.port }}
    {{- end }}
    
    {{- if .Values.networkPolicy.ingress.allowFromSpecificNamespaces }}
    {{- range .Values.networkPolicy.ingress.allowFromSpecificNamespaces }}
    # Allow traffic from specific namespaces
    - from:
      - namespaceSelector:
          matchLabels:
            {{- toYaml .labels | nindent 12 }}
      {{- if .podSelector }}
      - podSelector:
          matchLabels:
            {{- toYaml .podSelector | nindent 12 }}
      {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- end }}
    
    {{- if .Values.networkPolicy.ingress.allowFromPods }}
    {{- range .Values.networkPolicy.ingress.allowFromPods }}
    # Allow traffic from specific pods
    - from:
      - podSelector:
          matchLabels:
            {{- toYaml .labels | nindent 12 }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- end }}
    
    {{- if .Values.networkPolicy.ingress.allowFromIPBlocks }}
    {{- range .Values.networkPolicy.ingress.allowFromIPBlocks }}
    # Allow traffic from IP blocks
    - from:
      - ipBlock:
          cidr: {{ .cidr }}
          {{- if .except }}
          except:
            {{- toYaml .except | nindent 12 }}
          {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- end }}

  # EGRESS RULES - What traffic is allowed FROM this application
  egress:
    {{- if .Values.networkPolicy.egress.allowToInternet }}
    # Allow access to the internet
    - {}
    {{- end }}
    
    {{- if .Values.networkPolicy.egress.allowToDNS }}
    # Allow DNS lookups
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    
    {{- if .Values.networkPolicy.egress.allowToKubernetesAPI }}
    # Allow access to Kubernetes API server
    - to:
      - namespaceSelector:
          matchLabels:
            name: kube-system
      ports:
        - protocol: TCP
          port: 443
    {{- end }}
    
    {{- if .Values.networkPolicy.egress.allowToSameNamespace }}
    # Allow traffic to other pods in the same namespace
    - to:
      - namespaceSelector:
          matchLabels:
            name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.app.port }}
    {{- end }}
    
    {{- if .Values.networkPolicy.egress.allowToSpecificNamespaces }}
    {{- range .Values.networkPolicy.egress.allowToSpecificNamespaces }}
    # Allow traffic to specific namespaces
    - to:
      {{- if .toNamespaces }}
      {{- range .toNamespaces }}
      - namespaceSelector:
          matchLabels:
            {{- toYaml .labels | nindent 12 }}
      {{- end }}
      {{- end }}
      {{- if .toPods }}
      {{- range .toPods }}
      - podSelector:
          matchLabels:
            {{- toYaml .labels | nindent 12 }}
      {{- end }}
      {{- end }}
      {{- if .toIPBlocks }}
      {{- range .toIPBlocks }}
      - ipBlock:
          cidr: {{ .cidr }}
          {{- if .except }}
          except:
            {{- toYaml .except | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
