# Environment-specific values for production
replicaCount: 3

image:
  repository: ghcr.io/aryan-spanda/test-application
  tag: "latest"
  pullPolicy: Always

app:
  name: test-application
  version: "1.0.0"
  port: 3000
  
  env:
    NODE_ENV: production
    LOG_LEVEL: info

  # Health check configuration
  healthCheck:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  # Readiness probe configuration
  readinessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

  # Monitoring
  metrics:
    enabled: true
    path: /metrics
    port: 3000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - test-application
        topologyKey: kubernetes.io/hostname
