# Environment-specific values for production
replicaCount: 3

image:
  tag: "{{ .Values.global.imageTag | default "latest" }}"

app:
  env:
    NODE_ENV: production
    LOG_LEVEL: info

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - test-application
        topologyKey: kubernetes.io/hostname
