# Environment-specific values for staging
replicaCount: 2

image:
  tag: "latest"

ingress:
  enabled: true
  className: "nginx"
  host: "test-app-staging.spanda.local"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: test-app-staging-tls
      hosts:
        - test-app-staging.spanda.local

env:
  NODE_ENV: staging
  LOG_LEVEL: info
  FEATURE_FLAG_X: "true"
  API_RATE_LIMIT: "1000"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Enable autoscaling in staging for testing
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
