# Environment-specific values for development
replicaCount: 1

image:
  tag: "dev"

ingress:
  hosts:
    - host: test-app-dev.spanda.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: test-app-dev-tls
      hosts:
        - test-app-dev.spanda.local

app:
  env:
    NODE_ENV: development
    LOG_LEVEL: debug

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
