# Production environment values - maximum security
replicaCount: 3

# Enable microservices deployment mode
app:
  deploymentMode: microservices

image:
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: "nginx"
  host: "test-app.aryanpola.xyz"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-production"  # Corrected name
  tls:
    - secretName: test-app-prod-tls
      hosts:
        - test-app.aryanpola.xyz

env:
  NODE_ENV: production
  LOG_LEVEL: warn

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Network Policy - Production Environment
# Strict security with minimal required access
networkPolicy:
  enabled: true
  ingress:
    allowFromIngressController: true
    allowFromMonitoring: true
    allowFromSameNamespace: false  # Strict isolation in production
  egress:
    allowDNS: true
    allowToInternet: true
    allowHTTP: false  # HTTPS only in production
    # Add specific external services if needed
    customRules:
      - description: "Allow access to external payment API"
        toIPBlocks:
          - cidr: "203.0.113.0/24"  # Example payment gateway IP range
        ports:
          - port: 443
            protocol: TCP
replicaCount: 3

image:
  # tag: managed by ArgoCD Image Updater via Helm parameters.
  pullPolicy: Always

ingress:
  enabled: true
  className: "nginx"
  host: "test-app.spanda.local"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: test-app-tls
      hosts:
        - test-app.spanda.local

env:
  NODE_ENV: production
  LOG_LEVEL: warn

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - test-application
        topologyKey: kubernetes.io/hostname
