# Application CI/CD Workflow
# This is the ONLY workflow file the developer needs
# It calls the reusable platform workflow with app-specific parameters

name: Build and Deploy Test Application

on:
  push:
    branches: [ main, cicd ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'RESTRUCTURE.md'
      - 'PLATFORM-REQUIREMENTS.md'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  call-platform-workflow:
    name: Deploy via Platform Workflow
    # Use the reusable workflow from the config repository
    uses: aryan-spanda/Spanda-config/.github/workflows/reusable-platform-ci-cd.yml@main
    with:
      # Application-specific parameters
      app_name: "test-application"
      docker_image_name: "aryanpola/sample-application"
      config_repo: "aryan-spanda/Spanda-config"
      target_branch: ${{ github.ref_name == 'cicd' && 'cicd' || 'main' }}
      node_version: "18"
      dockerfile_path: "./Dockerfile"
      docker_context: "."
    secrets:
      # Pass the required secrets to the platform workflow
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
